load(
    "//bazel:dist.bzl",
    "linux_aarch64_dist",
    "linux_x86_64_dist",
    "macos_aarch64_dist",
    "windows_x86_64_dist",
)

package(default_visibility = ["//visibility:public"])

exports_files([
    "bcr/modules/watchman/2026.07.06.00/patches/watchman-bazel.patch",
])

linux_x86_64_dist(
    name = "watchman-x86_64-linux-gnu",
    srcs = ["@watchman"],
)

linux_aarch64_dist(
    name = "watchman-aarch64-linux-gnu",
    srcs = ["@watchman"],
)

macos_aarch64_dist(
    name = "watchman-aarch64-apple-darwin",
    srcs = ["@watchman"],
)

windows_x86_64_dist(
    name = "watchman-x86_64-windows-gnu",
    srcs = ["@watchman"],
)

filegroup(
    name = "dist",
    srcs = [
        ":watchman-aarch64-apple-darwin",
        ":watchman-aarch64-linux-gnu",
        ":watchman-x86_64-linux-gnu",
        ":watchman-x86_64-windows-gnu",
    ],
)
